/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import gestion.GestionProgramas;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tato
 */
public class BuscarPrograma extends javax.swing.JFrame {

    /**
     * Creates new form BuscarPrograma
     */
    private GestionProgramas gestorProgramas= new GestionProgramas();
    public BuscarPrograma() {
        initComponents();
    }
    public void setModifyButtons(){
        this.jButtonEliminar.setVisible(false);
        this.jButtonBuscarPrograma.setVisible(false);
    }
    public void setDeleteButtons(){
        this.jButtonModificar.setVisible(false);
        this.jButtonBuscarPrograma.setVisible(false);
    }
    public void setSearchButtons(){
        this.jButtonEliminar.setVisible(false);
        this.jButtonModificar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscarPrograma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscarPrograma = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBuscarPrograma.setText("Buscar");
        jButtonBuscarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProgramaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        getContentPane().add(jTextFieldBuscarPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 250, 30));

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProgramaActionPerformed
        // TODO add your handling code here:
        String strBuscarPrograma = jTextFieldBuscarPrograma.getText();
        //System.out.println(buscarPrograma);
        try {            
            String datos[]= gestorProgramas.buscarPrograma(strBuscarPrograma);
            
            String codigo = datos[0];
            String nombre = datos[1];
            boolean acreditado= Boolean.valueOf(datos[2]);
            boolean presencial= Boolean.valueOf(datos[3]);
            boolean online = Boolean.valueOf(datos[4]);
            MostrarPrograma  mostrarPrograma = new MostrarPrograma(this, true);
            mostrarPrograma.setAtributos(codigo, nombre, acreditado, presencial, online);
            mostrarPrograma.disableButtons();
            mostrarPrograma.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {
            Logger.getLogger(BuscarPrograma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonBuscarProgramaActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        String strBuscarPrograma = jTextFieldBuscarPrograma.getText();
        try {            
            String datos[]= gestorProgramas.buscarPrograma(strBuscarPrograma);
            
            String codigo = datos[0];
            String nombre = datos[1];
            boolean acreditado= Boolean.valueOf(datos[2]);
            boolean presencial= Boolean.valueOf(datos[3]);
            boolean online = Boolean.valueOf(datos[4]);
            MostrarPrograma  mostrarPrograma = new MostrarPrograma(this, true);
            mostrarPrograma.setAtributos(codigo, nombre, acreditado, presencial, online);
            mostrarPrograma.deleteButtons();
            mostrarPrograma.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {
            Logger.getLogger(BuscarPrograma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String strBuscarPrograma = jTextFieldBuscarPrograma.getText();
        try {            
            String datos[]= gestorProgramas.buscarPrograma(strBuscarPrograma);
            
            String codigo = datos[0];
            String nombre = datos[1];
            boolean acreditado= Boolean.valueOf(datos[2]);
            boolean presencial= Boolean.valueOf(datos[3]);
            boolean online = Boolean.valueOf(datos[4]);
            MostrarPrograma  mostrarPrograma = new MostrarPrograma(null, true);
            mostrarPrograma.setAtributos(codigo, nombre, acreditado, presencial, online);
            mostrarPrograma.modifyButtons();
            mostrarPrograma.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {
            Logger.getLogger(BuscarPrograma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        Programas prog = new Programas();
        prog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPrograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarPrograma;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldBuscarPrograma;
    // End of variables declaration//GEN-END:variables

    
}
