package vista;

import gestion.GestionEstudiantes;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import negocio.Estudiante;


public class Estudiantes extends javax.swing.JFrame {

    
    private GestionEstudiantes gestor= new GestionEstudiantes();
    private String pathImage =null;
    
    public Estudiantes() throws IOException {
        initComponents();
        cargarValoresIniciales();
        cargarEstudiantes(0);
    }
    // Methode to resize imageIcon with the same size of a Jlabel
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabelNombreFoto.getWidth(), jLabelNombreFoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    private void cargarEstudiantes(int i) throws IOException{
        
        ArrayList<String[]> Estudiantes = gestor.buscarTodos();
        String[] aux = Estudiantes.get(i);
        for (int j = 0; j < Estudiantes.size(); j++) {
            this.jTextFieldCodigo.setText(aux[0]);
            this.jTextFieldNombres.setText(aux[1]);
            this.jTextFieldApellidos.setText(aux[2]);
            this.jComboBoxCarrera.setSelectedItem(aux[3]);
            this.jTextFieldDireccion.setText(aux[4]);
            this.jPasswordField1.setText(aux[5]);
            this.jTextFieldCelular.setText(aux[6]);
            this.jTextFieldEmail.setText(aux[7]);
            this.jLabelNombreFoto.setIcon(ResizeImage("src/archivos/" + aux[8]));
            this.jTextFieldEstudianteActual.setText(Integer.toString(i+1));
            pathImage = "src/archivos/" + aux[8];
        }
    }
    
    
    private Estudiante crearEstudiante(){
        String codigo = jTextFieldCodigo.getText();
        String nombre = jTextFieldNombres.getText();
        String apellidos = jTextFieldApellidos.getText();
        String programa= (String) jComboBoxCarrera.getSelectedItem();
        String direccion= jTextFieldDireccion.getText();
        String password = new String(jPasswordField1.getPassword());
        String celular = jTextFieldCelular.getText();
        String email= jTextFieldEmail.getText();
        String []iconPath = pathImage.split("/");
        String nombreFoto= iconPath[iconPath.length-1];
        Estudiante estudiante = new Estudiante(codigo, nombre, apellidos, programa, direccion, password, celular, email, nombreFoto);
        return estudiante;
    }
    
    private void cargarValoresIniciales(){
        
        String filePath = "src/archivos/misProgramas.txt";
        File file = new File(filePath);
        ArrayList<String> alist=new ArrayList<>();
        try {
           BufferedReader br = new BufferedReader(new FileReader(file));
           String line = null;
           while ((line = br.readLine()) != null) {
               String search []= line.split(",");
               alist.add(search[1]);
           }
           String[] lineArray = new String[alist.size()];
           lineArray = alist.toArray(lineArray);
           DefaultComboBoxModel mod= new DefaultComboBoxModel(lineArray);
           jComboBoxCarrera.setModel(mod);
        } catch (Exception ex) {
            System.err.println("error");
            //Logger.getLogger(TextFileDataToJTable.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          jLabelNombreFoto.setIcon(ResizeImage("src/archivos/unknown.jpeg"));
          pathImage = "src/archivos/unknown.jpeg";

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNombres = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jComboBoxCarrera = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabelNombreFoto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonAnterior = new javax.swing.JButton();
        jTextFieldEstudianteActual = new javax.swing.JTextField();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonNuevoEstudiante = new javax.swing.JButton();
        jButtonModificarEstudiante = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVerTodos = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonChangePic = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(16, 24, 26));
        setMinimumSize(new java.awt.Dimension(1020, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setText("Celular");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 280, -1));

        jTextFieldNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombresActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 280, -1));
        getContentPane().add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 280, -1));
        getContentPane().add(jTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 280, -1));

        jComboBoxCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 250, -1));

        jLabel5.setText("Carrera");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabelNombreFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNombreFotoMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNombreFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 230, 230));

        jLabel6.setText("Apellidos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 250, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 250, -1));

        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 250, -1));

        jButtonAnterior.setText("-");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, 30));

        jTextFieldEstudianteActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstudianteActualActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEstudianteActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, -1));

        jButtonSiguiente.setText("+");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 40, 30));

        jButtonNuevoEstudiante.setText("Guardar");
        jButtonNuevoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 120, -1));

        jButtonModificarEstudiante.setText("Modificar");
        jButtonModificarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 140, -1));

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 140, -1));

        jButtonVerTodos.setText("Ver Todos");
        jButtonVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerTodosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 140, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 120, -1));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        jButtonChangePic.setText("Cambiar");
        jButtonChangePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePicActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChangePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(220, 189, 18));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 1000, 140));

        jPanel2.setBackground(new java.awt.Color(214, 171, 34));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1000, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombresActionPerformed

    private void jComboBoxCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCarreraActionPerformed

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

    private void jButtonChangePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePicActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.dir")));
        
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png","jpeg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabelNombreFoto.setIcon(ResizeImage(path));
            pathImage = path;
        } //if the user click on save in Jfilechooser
        
        else if (result == JFileChooser.CANCEL_OPTION) {

            System.out.println("No File Select");
        }

    }//GEN-LAST:event_jButtonChangePicActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        VistaPrincipal vp= new VistaPrincipal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonNuevoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoEstudianteActionPerformed
        Estudiante estudiante= crearEstudiante();
        this.gestor.crearEstudiante(estudiante);
    }//GEN-LAST:event_jButtonNuevoEstudianteActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        int cargar= Integer.parseInt(this.jTextFieldEstudianteActual.getText());
        try {
            if (cargar<2){
                cargar=2;
            }
            this.cargarEstudiantes(cargar-2);
        } catch (IOException ex) {
            Logger.getLogger(Estudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        int cargar= Integer.parseInt(this.jTextFieldEstudianteActual.getText());
        try {
            int secure = this.gestor.buscarTodos().size();
            if (cargar>=secure){
                cargar= cargar-1;
                }
            this.cargarEstudiantes(cargar);
        } catch (IOException ex) {
            Logger.getLogger(Estudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jTextFieldEstudianteActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstudianteActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstudianteActualActionPerformed

    private void jLabelNombreFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNombreFotoMouseClicked
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.dir")));
        
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabelNombreFoto.setIcon(ResizeImage(path));
            pathImage = path;
        } //if the user click on save in Jfilechooser
        
        else if (result == JFileChooser.CANCEL_OPTION) {

            System.out.println("No File Select");
        }
    }//GEN-LAST:event_jLabelNombreFotoMouseClicked

    private void jButtonVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerTodosActionPerformed
        // TODO add your handling code here:
        TablaEstudiantes todosEstudiantes= new TablaEstudiantes(null, true);
        todosEstudiantes.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVerTodosActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String codigo = JOptionPane.showInputDialog(this, "Inserte el Codigo");
        try {
            int posicion= this.gestor.buscarPosicion(codigo);
            cargarEstudiantes(posicion);
        } catch (IOException ex) {
            Logger.getLogger(Estudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonModificarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEstudianteActionPerformed
      
        Estudiante estudiante = crearEstudiante();
        try {
            this.gestor.modificarEstudiante(estudiante,2);
        } catch (IOException ex) {
            Logger.getLogger(Estudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonModificarEstudianteActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        
        Estudiante estudiante = crearEstudiante();
        try {
            this.gestor.modificarEstudiante(estudiante,1);
            cargarEstudiantes(0);
        } catch (IOException ex) {
            Logger.getLogger(Estudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Estudiantes dialog = new Estudiantes();
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Estudiantes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonChangePic;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificarEstudiante;
    private javax.swing.JButton jButtonNuevoEstudiante;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonVerTodos;
    private javax.swing.JComboBox<String> jComboBoxCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNombreFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstudianteActual;
    private javax.swing.JTextField jTextFieldNombres;
    // End of variables declaration//GEN-END:variables
}
