package vista;

public class Inscripciones extends javax.swing.JFrame {

   
    public Inscripciones() {

        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrear = new javax.swing.JButton();
        jButtonVerTodas = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonModificarInscripcion = new javax.swing.JButton();
        jButtonEliminarInscripcion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonBuscarUna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCrear.setText("Crear Inscripción");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButtonVerTodas.setText("Ver Todas");
        jButtonVerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerTodasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, 30));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 30));

        jButtonModificarInscripcion.setText("Modificar");
        jButtonModificarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarInscripcionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, -1));

        jButtonEliminarInscripcion.setText("Eliminar");
        jButtonEliminarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarInscripcionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, -1));

        jPanel1.setBackground(new java.awt.Color(240, 200, 38));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBuscarUna.setText("Ver Inscripción");
        jButtonBuscarUna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarUnaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarUna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerTodasActionPerformed
        TablaInscripciones tabla= new TablaInscripciones(null, rootPaneCheckingEnabled);
        tabla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVerTodasActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        BuscarInscripcion crear= new BuscarInscripcion(null, rootPaneCheckingEnabled);
        crear.botonesGuardar();
        crear.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonEliminarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarInscripcionActionPerformed
        BuscarInscripcion eliminar= new BuscarInscripcion(null, rootPaneCheckingEnabled);
        eliminar.botonesEliminar();
        eliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEliminarInscripcionActionPerformed

    private void jButtonModificarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarInscripcionActionPerformed
        BuscarInscripcion modificar= new BuscarInscripcion(null, rootPaneCheckingEnabled);
        modificar.botonesModificar();
        modificar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonModificarInscripcionActionPerformed

    private void jButtonBuscarUnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarUnaActionPerformed
        BuscarInscripcion buscar= new BuscarInscripcion(null, rootPaneCheckingEnabled);
        buscar.botonesBuscar();
        buscar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBuscarUnaActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        VistaPrincipal vp= new VistaPrincipal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inscripciones dialog = new Inscripciones();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarUna;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEliminarInscripcion;
    private javax.swing.JButton jButtonModificarInscripcion;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonVerTodas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
