package vista;

import gestion.GestionProgramas;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.Programa;


public class MostrarPrograma extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    private final GestionProgramas gestor= new GestionProgramas();
    
    
    public MostrarPrograma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jButtonDelete.setVisible(false);
        this.jButtonModificar.setVisible(false);
    }
    public void setAtributos(String codigo,String nombre, boolean acreditado, boolean presencial, boolean online){
        this.jTextFieldCodigoPrograma.setText(codigo);
        this.jTextFieldNombrePrograma.setText(nombre);
        this.jCheckBoxProgramaAcreditado.setSelected(acreditado);
        this.jCheckBoxPresencial.setSelected(presencial);
        this.jCheckBoxOnline.setSelected(online);
    }
        
    public void disableButtons(){
        this.jButtonGuardar.setEnabled(false);
        this.jButtonModificar.setVisible(false);
        this.jButtonLimpiar.setEnabled(false);
        this.jButtonDelete.setVisible(false);
        this.jCheckBoxOnline.setEnabled(false);
        this.jCheckBoxPresencial.setEnabled(false);
        this.jCheckBoxProgramaAcreditado.setEnabled(false);
    }
    public void deleteButtons(){
        this.jButtonGuardar.setVisible(false);
        this.jButtonLimpiar.setVisible(false);
        this.jButtonDelete.setVisible(true);
        this.jButtonModificar.setVisible(false);

    }
    public void modifyButtons(){
        this.jButtonGuardar.setVisible(false);
        this.jButtonModificar.setVisible(true);
        this.jButtonLimpiar.setVisible(true);
        this.jButtonDelete.setVisible(false);
    }
    public void saveButtons(){
        this.jButtonGuardar.setVisible(true);
        this.jButtonModificar.setVisible(false);
        this.jButtonLimpiar.setVisible(true);
        this.jButtonDelete.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombrePrograma = new javax.swing.JTextField();
        jTextFieldCodigoPrograma = new javax.swing.JTextField();
        jCheckBoxProgramaAcreditado = new javax.swing.JCheckBox();
        jCheckBoxPresencial = new javax.swing.JCheckBox();
        jCheckBoxOnline = new javax.swing.JCheckBox();
        jButtonGuardar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombrePrograma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreProgramaFocusLost(evt);
            }
        });
        jTextFieldNombrePrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNombreProgramaMouseClicked(evt);
            }
        });
        jTextFieldNombrePrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreProgramaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombrePrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, 30));

        jTextFieldCodigoPrograma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoProgramaFocusLost(evt);
            }
        });
        jTextFieldCodigoPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCodigoProgramaMouseClicked(evt);
            }
        });
        jTextFieldCodigoPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoProgramaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigoPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 44, 250, 30));

        jCheckBoxProgramaAcreditado.setText("Acreditada");
        jCheckBoxProgramaAcreditado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProgramaAcreditadoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxProgramaAcreditado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jCheckBoxPresencial.setText("Presencial");
        getContentPane().add(jCheckBoxPresencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jCheckBoxOnline.setText("Online");
        getContentPane().add(jCheckBoxOnline, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 80, -1));

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, -1));

        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 80, -1));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 80, -1));

        jPanel1.setBackground(new java.awt.Color(219, 185, 52));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreProgramaActionPerformed
             
    }//GEN-LAST:event_jTextFieldNombreProgramaActionPerformed

    private void jTextFieldCodigoProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoProgramaActionPerformed

    private void jTextFieldCodigoProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProgramaMouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoProgramaMouseClicked

    private void jTextFieldCodigoProgramaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProgramaFocusLost
                

    }//GEN-LAST:event_jTextFieldCodigoProgramaFocusLost

    private void jTextFieldNombreProgramaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreProgramaFocusLost
      
    }//GEN-LAST:event_jTextFieldNombreProgramaFocusLost

    private void jTextFieldNombreProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreProgramaMouseClicked
        
    }//GEN-LAST:event_jTextFieldNombreProgramaMouseClicked

    private void jCheckBoxProgramaAcreditadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProgramaAcreditadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBoxProgramaAcreditadoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        
        String codigo=jTextFieldCodigoPrograma.getText();
        String nombre= jTextFieldNombrePrograma.getText();
        boolean acreditado = jCheckBoxProgramaAcreditado.isSelected();
        boolean presencial = jCheckBoxPresencial.isSelected();
        boolean online = jCheckBoxOnline.isSelected();
        //this.gestor.crearPrograma(codigo, nombre, acreditado, presencial, online);
        Programa prog = new Programa(codigo,nombre,acreditado,presencial,online);
        this.gestor.crearPrograma(prog);
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        
        new Programas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        this.jTextFieldCodigoPrograma.setText("");
        this.jTextFieldNombrePrograma.setText("");
        this.jCheckBoxProgramaAcreditado.setSelected(false);
        this.jCheckBoxPresencial.setSelected(false);
        this.jCheckBoxOnline.setSelected(false);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String codigo=jTextFieldCodigoPrograma.getText();
        String nombre= jTextFieldNombrePrograma.getText();
        boolean acreditado = jCheckBoxProgramaAcreditado.isSelected();
        boolean presencial = jCheckBoxPresencial.isSelected();
        boolean online = jCheckBoxOnline.isSelected();
        Programa prog = new Programa(codigo, nombre, acreditado, presencial, online);
        try {
            this.gestor.modificarPrograma(prog, 1);
        } catch (IOException ex) {
            Logger.getLogger(MostrarPrograma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        String codigo=jTextFieldCodigoPrograma.getText();
        String nombre= jTextFieldNombrePrograma.getText();
        boolean acreditado = jCheckBoxProgramaAcreditado.isSelected();
        boolean presencial = jCheckBoxPresencial.isSelected();
        boolean online = jCheckBoxOnline.isSelected();
        Programa prog = new Programa(codigo, nombre, acreditado, presencial, online);
        try {
            this.gestor.modificarPrograma(prog, 2);
        } catch (IOException ex) {
            Logger.getLogger(MostrarPrograma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MostrarPrograma dialog = new MostrarPrograma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JCheckBox jCheckBoxOnline;
    private javax.swing.JCheckBox jCheckBoxPresencial;
    private javax.swing.JCheckBox jCheckBoxProgramaAcreditado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodigoPrograma;
    private javax.swing.JTextField jTextFieldNombrePrograma;
    // End of variables declaration//GEN-END:variables
}
